[package]
name = "vicky3-mod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
nightly = []

[dependencies]
sis = { path = "sis" }
cfg-if = "1.0.0"
into_string = "2.0.0"
itertools = "0.10.5"
jomini = "0.21.0"
once_cell = "1.17.0"
ouroboros = "0.15.5"
serde = { version = "1.0.152", features = ["derive"] }
